#!/bin/zsh

if [[ "$OSTYPE" == linux* ]]; then
  active_window_id="$(xdotool getactivewindow)"
  active_window_title=$(xdotool getwindowname "$active_window_id")
  format_and_select_window() {
    # Execute awk to format input and replace '|' with '/'
    awk 'BEGIN { FS=" "; OFS="|" } 
        {
          gsub(/\|/, "/", $0);
          split($3, array, ".");
          $3=array[1];
          if ($3 == "nemo-desktop") next;
          $1=substr($1,1,10); 
          $2=substr($2,1,1); 
          $3=substr($3,1,20); 
          $4=substr($4,1,12); 
          fifth_col=$5; 
          for(i=6;i<=NF;i++) 
            fifth_col=fifth_col " " $i; 
          printf "%-10s|%-1s|%-20s|%-12s|%s\n", $1, $2, $3, $4, fifth_col; 
        }' |
      fzf -d '\|' --with-nth=3,5.. \
        --layout=reverse \
        --height=70% \
        --exact \
        --preview 'echo {} | fold -w $FZF_PREVIEW_COLUMNS' \
        --bind 'enter:become(wmctrl -ia {1} && echo "success")' \
        --bind 'space:become(wmctrl -ia {1} && echo "success")' \
        --bind 'one:become(wmctrl -ia {1} && echo "success")'
  }
  if [[ "$(format_and_select_window < <(wmctrl -lx))" == "success" ]]; then
    xdotool windowminimize "$active_window_id"
  fi
elif [[ "$OSTYPE" == darwin* ]]; then
  selected_id=$(yabai -m query --windows | jq -r '.[] | "\(.id)\t\(.app)\t\(.title)"' | awk -F'\t' '{printf "%-7s\t%-24.24s\t%s\n", $1, $2, $3}' |
    fzf --with-nth 2,3 \
    --delimiter '\t' \
    --preview 'echo {}' \
    --layout=reverse \
    --height=70% \
    --bind 'space:accept' \
    --bind one:accept --exact | cut -f1)
  yabai -m window --focus "${(MS)selected_id##[[:graph:]]*[[:graph:]]}"
fi
